import re

INPUT_PATH = r"d:\Workspace\SkinEngine\knowledge\AI 스킨케어 분석용 정밀 데이터베이스 설계 리포트.md"
OUTPUT_PATH = r"d:\Workspace\SkinEngine\knowledge\sanitized_clinical_report.md"

def sanitize():
    try:
        with open(INPUT_PATH, "r", encoding="utf-8") as f:
            content = f.read()
            
        # 1. First, replace the weird escaped structural elements
        # These are likely generated by an AI that over-escaped everything
        content = content.replace(r"\---", "\n---\n")
        content = content.replace(r"\#\#\#", "\n###")
        content = content.replace(r"\#\#", "\n##")
        content = content.replace(r"\#", "\n#")
        
        # 2. Fix the tables. Tables look like | Col | Col |
        # But they might be joined on one line.
        # We look for | followed by text and then |
        # Actually, let's just restore the newlines for table rows
        # If we see "| " preceded by something that isn't a newline, it's likely a join
        content = re.sub(r"(?<!\n) \| ", "\n| ", content)
        
        # 3. Clean up the escapes for common characters
        content = content.replace(r"\.", ".").replace(r"\_", "_").replace(r"\|", "|").replace(r"\-", "-")
        
        # 4. Clean up bold markers if they are escaped \*\*
        content = content.replace(r"\*", "*")
        
        # 5. Fix double newlines
        content = re.sub(r"\n\s*\n", "\n\n", content)
        
        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"[Success] Sanitized file saved to {OUTPUT_PATH}")
        return True
    except Exception as e:
        print(f"[Error] Sanitization failed: {e}")
        return False

if __name__ == "__main__":
    sanitize()
